#!/bin/sh
PS5="$(tty -s && tput setaf 5)+\$(echo \${BASH_SOURCE[0]}:\${LINENO}) $(\
 tty -s && tput setaf 3)\$(echo \${LINENO} | sed 's/\$/@/g')\$(echo \${BASH_LINENO[*]} | awk '{\$NF=\"\"; print \$0}' | sed 's/ \$//g'| sed 's/ /@/g')$(tty -s && tput sgr0):$(tty -s && tput setaf 5)\$(echo \${FUNCNAME[*]} | sed 's/ /\//g')$(tty -s && tput sgr0)$ "; export PS5

export PS6="+\033[01;33m\${LINENO//$/@}\$(echo \${BASH_LINENO[*]} | awk '{\$NF=\"\"; print \$0}' | sed   's/ \$//g'| sed 's/ /@/g')\033[00m:\033[01;35m\$(echo \${FUNCNAME[*]} | sed 's/ /\//g  ')\033[00m$ "

export PS7="$(tty -s && tput setaf 5)+\$(echo \${BASH_SOURCE[0]}:\${LINENO}) $(tty -s && tput setaf 3)\$(echo \${LINENO} | sed 's/\$/@/g')\$(echo \${BASH_LINENO[*]} | awk '{\$NF=\"\"; print \$0}' | sed 's/ \$//g'| sed 's/ /@/g')$(tty -s && tput sgr0):$(tty -s && tput setaf 5)\$(echo \${FUNCNAME[*]} | sed 's/ /\//g')$(tty -s && tput sgr0)$ "

export PS8="+(\${BASH_SOURCE}:\${LINENO}):|:\${FUNCNAME[0]:+\${FUNCNAME[0]}():|:}"

PS9='+ '

PS10='(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]} - [${SHLVL},${BASH_SUBSHELL}, $?]'

#######################################
# PS4:              debugging set -x PS
# shellcheck disable=SC2089
PS11="$(tty -s && tput setaf 5)+\$(echo \${BASH_SOURCE[0]}:\${LINENO}) $(
  tty -s && tput setaf 3
)\$(echo \${LINENO} | sed 's/\$/@/g')\$(echo \${BASH_LINENO[*]} | \
  awk '{\$NF=\"\"; print \$0}' | sed 's/ \$//g'| sed 's/ /@/g')$(
  tty -s && tput sgr0
):$(tty -s && tput setaf 5)\$(echo \${FUNCNAME[*]} | sed 's/ /\//g')$(tty -s && tput sgr0)$ "

export PS12="+ [${Magenta}\$(basename \"\${BASH_SOURCE[0]}\")${Reset}][${Magenta}\${LINENO}${Reset}]\
[${Yellow}\$(echo \${BASH_LINENO[*]} | awk '{\$NF=\"\"; print \$0}' | sed 's/ \$//g'| sed 's/ /@/g')${Reset}]\
${Green}$ ${Reset}"

export PS13
